version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.26"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
