# Example: Dapr Azure SQL state store component
# Apply to your cluster after creating the Kubernetes secret with the connection string.
#
# Prerequisites:
#   1. Azure SQL Server + database (create via Azure Portal or CLI)
#   2. Create K8s secret: kubectl create secret generic azuresql-secret \
#        --from-literal=connectionString='Server=tcp:YOUR_SERVER.database.windows.net,1433;Database=YOUR_DB;User Id=YOUR_USER;Password=YOUR_PASSWORD;Encrypt=yes;'
#   3. Apply this component (same namespace as the secret)
#
# For production, use Azure AD (useAzureAD: true) with Managed Identity.
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.sqlserver
  version: v1
  metadata:
    # Option 1: SQL Server credentials (development)
    - name: connectionString
      secretKeyRef:
        name: azuresql-secret
        key: connectionString

    # Option 2: Azure AD (recommended for AKS)
    # - name: useAzureAD
    #   value: "true"
    # - name: connectionString
    #   value: "sqlserver://<server>.database.windows.net:1433?database=daprstate"
    # - name: azureTenantId
    #   secretKeyRef:
    #     name: azure-ad-secret
    #     key: tenantId
    # - name: azureClientId
    #   secretKeyRef:
    #     name: azure-ad-secret
    #     key: clientId
    # - name: azureClientSecret
    #   secretKeyRef:
    #     name: azure-ad-secret
    #     key: clientSecret

    # Optional metadata
    - name: tableName
      value: "state"
    - name: schema
      value: "dbo"
    - name: keyLength
      value: "200"
